name: key

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Run autorun.py
        run: |
          cd pages
          python upload.py
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the secret
        run: echo "The secret is ${{ secrets.FIRESTORE_KEY }}"
