name: key

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Run autorun.py
        working-directory: haze_removal
        run: python haze_removal/auto.py
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the secret
        run: echo "The secret is ${{ secrets.FIRESTORE_KEY }}"
